name: Python SDK CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, "3.9-dev"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install pytest
      run: pip install responses
      run: pip install pytest-cov
      run: pip install coveralls
      run: pip install requests
      run: pip install pyjwt
      run: pip install uuid
    
    - name: Test with pytest
      run: |
        pytest --cov=tests/
      run: coveralls